## 1. 서울시_우리마을가게_상권분석서비스(상권-점포)_2020년_4분기 데이터 불러오기

In [1]:
import numpy as np
import pandas as pd

In [2]:
market=pd.read_csv("서울시_우리마을가게_상권분석서비스(상권-점포)_2020년.csv")

C:\Users\user\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
market.head()

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
0,2020,1,A,골목상권,1000001,계동길,CS300018,의약품,0,0,0,0,0,0,0
1,2020,1,D,발달상권,1001250,서울 은평구 불광역_3,CS300014,신발,0,0,0,0,0,0,0
2,2020,1,A,골목상권,1000001,계동길,CS300032,가전제품,1,1,0,0,0,0,0
3,2020,1,R,전통시장,1001392,동진시장,CS200034,여관,0,0,0,0,0,0,0
4,2020,1,U,관광특구,1001495,잠실 관광특구,CS200022,복권방,1,1,0,0,0,0,0

### 4분기 데이터만 추출

In [4]:
market=market[market['기준_분기_코드']==4]

### NaN(상권구분코드 K )삭제

In [5]:
idx=market[market['상권_구분_코드']=='K'].index

In [6]:
market=market.drop(idx)

In [7]:
market['상권_구분_코드'].unique()

array(['A', 'D', 'R', 'U'], dtype=object)

### 필요없는 열 삭제

In [8]:
market = market.drop(list(market.columns)[10:], axis=1)
market = market.drop(['상권_구분_코드', '상권_구분_코드_명', '상권_코드_명', '서비스_업종_코드', '서비스_업종_코드_명'], axis=1)
market.head()

        기준_년_코드  기준_분기_코드    상권_코드  점포_수  유사_업종_점포_수
276993     2020         4  1000022     1           1
276994     2020         4  1000055     0           0
276995     2020         4  1000056     7           9
276996     2020         4  1000064     2           2
276997     2020         4  1000087     0           0

## 2. 상권_코드(주소)별 점포수 집계

### 상권 코드 공백제거

In [9]:
market['상권_코드'].nunique()

2992

In [10]:
market['상권_코드'] = market['상권_코드'].astype(int)

In [11]:
market['상권_코드'].nunique()

1496

In [12]:
market_gr = market.groupby(market['상권_코드']).sum()
market_gr.head()

         기준_년_코드  기준_분기_코드  점포_수  유사_업종_점포_수
상권_코드
1000001   131300       260   201         212
1000002   135340       268   115         122
1000003   155540       308   284         299
1000004    86860       172    73          84
1000005    94940       188    76          80

In [13]:
market_gr.shape

(1496, 4)

### 연도, 분기 수정

In [14]:
market_gr['기준_년_코드'] = 2020
market_gr['기준_분기_코드'] = 4
market_gr = market_gr.reset_index()

In [15]:
market_gr.head()

     상권_코드  기준_년_코드  기준_분기_코드  점포_수  유사_업종_점포_수
0  1000001     2020         4   201         212
1  1000002     2020         4   115         122
2  1000003     2020         4   284         299
3  1000004     2020         4    73          84
4  1000005     2020         4    76          80

## 3. 상권코드를 행정동 코드로 변환

### 상권영역 데이터 불러오기

In [16]:
area=pd.read_csv('서울시 우리마을가게 상권분석서비스(상권영역).csv')

In [17]:
area.head()

,기준_년월_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,엑스좌표_값,와이좌표_값,시군구_코드,행정동_코드,형태정보
0,201810,R,전통시장,1001453,낙성대시장,196121,442084,11620,11620585,NaN
1,201810,R,전통시장,1001454,봉천제일종합시장,195147,442413,11620,11620595,NaN
2,201810,R,전통시장,1001474,도곡시장,204551,444227,11680,11680650,NaN
3,201810,R,전통시장,1001475,강남개포시장,206065,443310,11680,11680670,NaN
4,201810,R,전통시장,1001412,화곡본동시장,186203,449328,11500,11500590,NaN

In [18]:
area['상권_코드'].nunique()

1496

### 상권코드를 행정동 코드로 바꾸는 dictionary 생성

In [19]:
Dic=dict(zip(area['상권_코드'], area['행정동_코드']))

In [20]:
Dic

{1001453: 11620585,
 1001454: 11620595,
 1001474: 11680650,
 1001475: 11680670,
 1001412: 11500590,
 1001413: 11500593,
 1001414: 11500611,
 1001452: 11620575,
 1001415: 11500630,
 1001416: 11500640,
 1001423: 11545610,
 1001424: 11545630,
 1001425: 11545630,
 1001426: 11545670,
 1001427: 11545670,
 1001428: 11545690,
 1001429: 11545710,
 1001470: 11680510,
 1001372: 11380580,
 1001373: 11380590,
 1001374: 11380600,
 1001480: 11710650,
 1001440: 11590510,
 1001441: 11590510,
 1001442: 11590520,
 1001443: 11590530,
 1001444: 11590530,
 1001445: 11590540,
 1001446: 11590550,
 1001375: 11380640,
 1001376: 11380650,
 1001460: 11620685,
 1001461: 11620685,
 1001462: 11620725,
 1001463: 11620725,
 1001464: 11620745,
 1001465: 11620745,
 1001466: 11620765,
 1001467: 11620775,
 1001437: 11560680,
 1001438: 11560700,
 1001439: 11560710,
 1001417: 11530550,
 1001418: 11530550,
 1001419: 11530595,
 1001420: 11530730,
 1001421: 11530750,
 1001422: 11530770,
 1001476: 11710510,
 1001477: 11710550,
 1001478: 11710562,
 1001479: 11710600,
 1001396: 11470540,
 1001397: 11470560,
 1001398: 11470560,
 1001447: 11590560,
 1001448: 11590605,
 1001449: 11590630,
 1001451: 11590650,
 1001468: 11650590,
 1001469: 11650651,
 1001407: 11500520,
 1001408: 11500535,
 1001494: 11110615,
 1001450: 11590650,
 1001495: 11710566,
 1001496: 11680580,
 1001491: 11170650,
 1001492: 11140520,
 1001493: 11140590,
 1000334: 11305660,
 1000354: 11320513,
 1000355: 11320700,
 1000356: 11320700,
 1000357: 11320690,
 1000358: 11320690,
 1000364: 11320522,
 1000365: 11320521,
 1000366: 11320521,
 1000367: 11320521,
 1000368: 11320521,
 1000039: 11140550,
 1000040: 11140605,
 1000662: 11545700,
 1000835: 11620545,
 1000836: 11620575,
 1000527: 11470520,
 1000528: 11470530,
 1000288: 11290725,
 1000315: 11305630,
 1000316: 11305620,
 1000106: 11200670,
 1000107: 11200650,
 1000108: 11200690,
 1000522: 11470650,
 1000523: 11470540,
 1000524: 11470520,
 1000525: 11470540,
 1000753: 11590640,
 1000842: 11620745,
 1000843: 11620595,
 1000658: 11545710,
 1000659: 11545510,
 1000660: 11545630,
 1000661: 11545700,
 1000171: 11230560,
 1000172: 11230610,
 1000173: 11230610,
 1000174: 11230660,
 1000197: 11230660,
 1000198: 11230650,
 1000199: 11230660,
 1000200: 11230660,
 1000150: 11215760,
 1000151: 11215820,
 1000770: 11590680,
 1000771: 11590680,
 1000772: 11590680,
 1000773: 11590660,
 1000633: 11530530,
 1000872: 11650610,
 1000873: 11650510,
 1000176: 11230650,
 1000177: 11230660,
 1000178: 11230650,
 1000179: 11230730,
 1000180: 11230730,
 1000181: 11230720,
 1000183: 11230536,
 1000184: 11230570,
 1000185: 11230660,
 1000186: 11230600,
 1000187: 11230560,
 1000188: 11230560,
 1000347: 11305590,
 1000222: 11260565,
 1000223: 11260565,
 1000224: 11260565,
 1000329: 11305555,
 1000232: 11260600,
 1000233: 11260610,
 1000234: 11260610,
 1000634: 11530560,
 1000635: 11530560,
 1000119: 11200520,
 1000120: 11200660,
 1000121: 11200790,
 1000122: 11200790,
 1000123: 11200615,
 1000182: 11230536,
 1000341: 11305545,
 1000226: 11260620,
 1000227: 11260540,
 1000248: 11260565,
 1000249: 11260590,
 1000251: 11260610,
 1000252: 11260680,
 1000253: 11260570,
 1000254: 11260570,
 1000255: 11260580,
 1000363: 11320522,
 1000235: 11260600,
 1000236: 11260630,
 1000237: 11260630,
 1000654: 11545610,
 1000655: 11545510,
 1000656: 11545670,
 1000657: 11545610,
 1000124: 11200540,
 1000077: 11170530,
 1000078: 11170625,
 1000102: 11200550,
 1000103: 11200660,
 1000104: 11200660,
 1000105: 11200660,
 1000250: 11260600,
 1000936: 11680531,
 1000609: 11530760,
 1000610: 11530750,
 1000505: 11440590,
 1000506: 11440565,
 1000974: 11740540,
 1000739: 11590620,
 1000740: 11590630,
 1000741: 11590630,
 1000742: 11590630,
 1000743: 11590620,
 1000744: 11590660,
 1000844: 11650651,
 1000712: 11560610,
 1000511: 11470560,
 1000512: 11470600,
 1000513: 11470580,
 1000514: 11470580,
 1000515: 11470611,
 1000516: 11470610,
 1000922: 11680630,
 1000923: 11680630,
 1000924: 11680531,
 1000925: 11680565,
 1000926: 11680531,
 1000927: 11680565,
 1000597: 11500510,
 1000799: 11620585,
 1000471: 11440555,
 1000472: 11440565,
 1001006: 11740685,
 1001007: 11740520,
 1001008: 11740650,
 1001009: 11740650,
 1001010: 11740650,
 1000787: 11620605,
 1000543: 11470620,
 1000564: 11500540,
 1000565: 11500550,
 1000566: 11500593,
 1000567: 11500640,
 1000568: 11500640,
 1000569: 11500593,
 1000730: 11560630,
 1000794: 11620715,
 1000795: 11620765,
 1000796: 11620685,
 1000797: 11620685,
 1000798: 11620765,
 1000955: 11710632,
 1000782: 11620575,
 1000783: 11620545,
 1000784: 11620685,
 1000785: 11620695,
 1000889: 11680690,
 1000890: 11680690,
 1000747: 11590650,
 1000442: 11410640,
 1000959: 11710620,
 1000960: 11710620,
 1000961: 11710561,
 1000962: 11710570,
 1000963: 11710562,
 1000964: 11710620,
 1000665: 11545640,
 1000941: 11710632,
 1000942: 11710550,
 1000943: 11710610,
 1000944: 11710610,
 1000945: 11710610,
 1000946: 11710610,
 1000956: 11710641,
 1000957: 11710641,
 1000958: 11710620,
 1000467: 11440660,
 1000468: 11440710,
 1000469: 11440710,
 1000591: 11500640,
 1000748: 11590650,
 1000749: 11590620,
 1000750: 11590640,
 1000751: 11590640,
 1000852: 11650651,
 1000931: 11680580,
 1000932: 11680610,
 1000933: 11680730,
 1000978: 11740610,
 1000979: 11740610,
 1000980: 11740530,
 1000981: 11740580,
 1000982: 11740520,
 1000983: 11740640,
 1000697: 11560710,
 1000698: 11560700,
 1000603: 11470600,
 1000488: 11440660,
 1000489: 11440555,
 1000490: 11440555,
 1000491: 11440660,
 1000507: 11470580,
 1000508: 11470560,
 1000509: 11470560,
 1000592: 11500630,
 1000593: 11500630,
 1000594: 11500630,
 1000595: 11500603,
 1000596: 11500510,
 1000921: 11680610,
 1000934: 11680730,
 1000935: 11680580,
 1000968: 11740570,
 1000969: 11740590,
 1000970: 11740550,
 1000971: 11740600,
 1000972: 11740610,
 1000973: 11740600,
 1000718: 11560515,
 1000719: 11560620,
 1000720: 11560620,
 1000721: 11560620,
 1000722: 11560680,
 1000723: 11560690,
 1000476: 11440690,
 1000477: 11440740,
 1000880: 11650600,
 1000881: 11650600,
 1000882: 11650620,
 1000883: 11650520,
 1000884: 11650590,
 1000879: 11650610,
 1000885: 11650510,
 1000704: 11560585,
 1000510: 11470560,
 1000999: 11740620,
 1000681: 11545620,
 1000682: 11545620,
 1000895: 11680690,
 1000896: 11680521,
 1000897: 11680521,
 1000473: 11440585,
 1000474: 11440565,
 1000475: 11440700,
 1000786: 11620565,
 1000904: 11680650,
 1000905: 11680510,
 1000598: 11500615,
 1000599: 11500540,
 1000600: 11500590,
 1000601: 11500590,
 1000602: 11500630,
 1000703: 11560585,
 1000580: 11500620,
 1000641: 11530595,
 1000669: 11545610,
 1000670: 11545510,
 1000671: 11545640,
 1000672: 11545630,
 1000673: 11545610,
 1000667: 11545630,
 1000668: 11545610,
 1000800: 11620625,
 1000920: 11680630,
 1000438: 11410690,
 1000439: 11410555,
 1000440: 11410660,
 1000441: 11410655,
 1000906: 11680510,
 1000907: 11680531,
 1000908: 11680531,
 1000909: 11680531,
 1000910: 11680565,
 1000853: 11650621,
 1000891: 11680690,
 1000892: 11680670,
 1000965: 11710632,
 1000966: 11710510,
 1000443: 11410710,
 1000444: 11410555,
 1000445: 11410615,
 1000446: 11410720,
 1000447: 11410700,
 1000898: 11680521,
 1000666: 11545630,
 1000544: 11470620,
 1000545: 11470640,
 1000546: 11470640,
 1000547: 11470570,
 1000548: 11470570,
 1000470: 11440710,
 1000435: 11410700,
 1000436: 11410520,
 1000437: 11410700,
 1000975: 11740560,
 1000976: 11740550,
 1000977: 11740700,
 1000893: 11680655,
 1000570: 11500550,
 1000571: 11500550,
 1000572: 11500570,
 1000573: 11500570,
 1000611: 11530750,
 1000612: 11530760,
 1000699: 11560585,
 1000894: 11680640,
 1000700: 11560605,
 1000701: 11560670,
 1000702: 11560710,
 1000793: 11620765,
 1000984: 11740640,
 1000845: 11650651,
 1000517: 11470640,
 1000899: 11680510,
 1000900: 11680656,
 1000901: 11680656,
 1000902: 11680640,
 1000903: 11680690,
 1000578: 11500510,
 1000579: 11500510,
 1000967: 11740660,
 1000194: 11230750,
 1000256: 11260660,
 1000257: 11260655,
 1000258: 11260655,
 1000228: 11260520,
 1000306: 11290525,
 1000460: 11440610,
 1000010: 11110650,
 1000011: 11110710,
 1000012: 11110515,
 1000013: 11110615,
 1000014: 11110630,
 1000015: 11110640,
 1000044: 11140540,
 1000045: 11140550,
 1000046: 11140580,
 1000145: 11215847,
 1000538: 11470590,
 1000539: 11470590,
 1000540: 11470620,
 1000532: 11470630,
 1000760: 11590530,
 1000761: 11590530,
 1000411: 11380625,
 1000412: 11380580,
 1000413: 11380510,
 1000759: 11590530,
 1000359: 11320680,
 1000360: 11320511,
 1000874: 11650610,
 1000875: 11650540,
 1000876: 11650652,
 1000877: 11650560,
 1000878: 11650560,
 1000631: 11530595,
 1000663: 11545620,
 1000664: 11545640,
 1000535: 11470610,
 1000536: 11470650,
 1000537: 11470650,
 1000348: 11305590,
 1000349: 11305590,
 1000317: 11305620,
 1000338: 11305555,
 1000339: 11305610,
 1000340: 11305545,
 1000330: 11305575,
 1000331: 11305534,
 1000756: 11590651,
 1000636: 11530510,
 1000637: 11530550,
 1000638: 11530550,
 1000639: 11530750,
 1000738: 11590660,
 1000754: 11590651,
 1000755: 11590620,
 1000632: 11530550,
 1000733: 11590550,
 1000342: 11305590,
 1000343: 11305660,
 1000344: 11305660,
 1000345: 11305660,
 1000350: 11305630,
 1000351: 11305630,
 1000318: 11305600,
 1000319: 11305590,
 1000320: 11305555,
 1000307: 11290760,
 1000308: 11290810,
 1000332: 11305555,
 1000333: 11305610,
 1000398: 11380570,
 1000387: 11350670,
 1000388: 11350670,
 1000281: 11290685,
 1000282: 11290525,
 1000189: 11230560,
 1000190: 11230545,
 1000191: 11230536,
 1000192: 11230545,
 1000193: 11230705,
 1000346: 11305606,
 1000335: 11305535,
 1000336: 11305535,
 1000337: 11305545,
 1000303: 11290705,
 1000304: 11290705,
 1000305: 11290610,
 1000309: 11290725,
 1000311: 11290770,
 1000312: 11290715,
 1000041: 11140580,
 1000042: 11140625,
 1000043: 11140645,
 1000310: 11290725,
 1000389: 11380600,
 1000390: 11380631,
 1000352: 11320680,
 1000353: 11320515,
 1000529: 11470540,
 1000530: 11470540,
 1000531: 11470630,
 1000118: 11200535,
 1000095: 11200540,
 1000096: 11200550,
 1000097: 11200645,
 1000098: 11200615,
 1000099: 11200535,
 1000100: 11200520,
 1000101: 11200520,
 1000678: 11545670,
 1000679: 11545670,
 1000714: 11560670,
 1000715: 11560650,
 1000716: 11560630,
 1000717: 11560660,
 1000808: 11620775,
 1000812: 11620605,
 1000813: 11620665,
 1000814: 11620630,
 1000928: 11680670,
 1000929: 11680510,
 1000930: 11680650,
 1000499: 11440660,
 1000867: 11650581,
 1000868: 11650560,
 1000869: 11650621,
 1000552: 11500540,
 1000553: 11500540,
 1000624: 11530720,
 1000006: 11110600,
 1000007: 11110540,
 1000137: 11215710,
 1000138: 11215710,
 1000139: 11215780,
 1000231: 11260610,
 1000831: 11620725,
 1000832: 11620615,
 1000833: 11620595,
 1000809: 11620775,
 1000810: 11620665,
 1000855: 11650581,
 1000856: 11650652,
 1000857: 11650652,
 1000858: 11650610,
 1000859: 11650652,
 1000549: 11470611,
 1000500: 11440690,
 1000576: 11500520,
 1000577: 11500520,
 1000674: 11545630,
 1000675: 11545510,
 1000676: 11545690,
 1000677: 11545690,
 1000821: 11620695,
 1000008: 11110540,
 1000009: 11110540,
 1000762: 11590605,
 1000763: 11590605,
 1000764: 11590605,
 1000765: 11590605,
 1000326: 11305630,
 1000327: 11305630,
 1000037: 11140580,
 1000038: 11140635,
 1000109: 11200690,
 1000110: 11200690,
 1000175: 11230650,
 1000088: 11200560,
 1000089: 11200615,
 1000724: 11560690,
 1000815: 11620695,
 1000986: 11740660,
 1000987: 11740685,
 1000988: 11740685,
 1000989: 11740600,
 1000937: 11680590,
 1000991: 11740660,
 1000992: 11740700,
 1000993: 11740640,
 1000994: 11740610,
 1000995: 11740610,
 1000996: 11740610,
 1000997: 11740610,
 1000328: 11305555,
 1000313: 11290810,
 1000314: 11290810,
 1000382: 11350640,
 1000383: 11350640,
 1000094: 11200540,
 1000167: 11215860,
 1000774: 11590660,
 1000238: 11260630,
 1000239: 11260655,
 1000240: 11260655,
 1000241: 11260540,
 1000242: 11260540,
 1000243: 11260575,
 1000247: 11260565,
 1000990: 11740660,
 1000563: 11500540,
 1000846: 11650652,
 1000647: 11530790,
 1000648: 11530560,
 1000649: 11530510,
 1000650: 11530780,
 1000998: 11740570,
 1000653: 11530720,
 1000752: 11590620,
 1000680: 11545670,
 1000829: 11620725,
 1000519: 11470510,
 1000520: 11470630,
 1000521: 11470650,
 1000140: 11215847,
 1000141: 11215840,
 1000142: 11215847,
 1000143: 11215710,
 1000144: 11215840,
 1000732: 11560515,
 1000554: 11500540,
 1000555: 11500540,
 1000556: 11500593,
 1000216: 11230660,
 1000168: 11230710,
 1000169: 11230710,
 1000170: 11230536,
 1000022: 11110680,
 1000651: 11530595,
 1000616: 11530760,
 1000518: 11470680,
 1000492: 11440680,
 1000493: 11440680,
 1000494: 11440660,
 1000495: 11440660,
 1000496: 11440655,
 1000729: 11560515,
 1000501: 11440700,
 1000502: 11440730,
 1000503: 11440680,
 1000504: 11440660,
 1000688: 11560550,
 1000689: 11560560,
 1000830: 11620725,
 1000062: 11170700,
 1000063: 11170685,
 1000028: 11140670,
 1000029: 11140670,
 1000766: 11590560,
 1000870: 11650621,
 1000245: 11260575,
 1000626: 11530530,
 1000627: 11530530,
 1000628: 11530530,
 1000629: 11530530,
 1000630: 11530530,
 1000871: 11650621,
 1000841: 11620745,
 1000497: 11440660,
 1000498: 11440690,
 1000581: 11500550,
 1000816: 11620735,
 1000817: 11620665,
 1000818: 11620665,
 1000819: 11620645,
 1000780: 11620585,
 1000781: 11620585,
 1000938: 11680521,
 1000939: 11680565,
 1000613: 11530750,
 1000614: 11530740,
 1000615: 11530760,
 1000533: 11470630,
 1000534: 11470590,
 1000625: 11530560,
 1000034: 11140645,
 1000035: 11140625,
 1000036: 11140625,
 1000384: 11350640,
 1000217: 11230660,
 1000218: 11230720,
 1000219: 11230740,
 1000220: 11230740,
 1000361: 11320690,
 1000362: 11320690,
 1000834: 11620595,
 1000820: 11620695,
 1000483: 11440710,
 1000484: 11440720,
 1000847: 11650581,
 1000848: 11650530,
 1000849: 11650530,
 1000850: 11650510,
 1000851: 11650652,
 1001004: 11740650,
 1001005: 11740685,
 1000424: 11380632,
 1000391: 11380552,
 1000392: 11380551,
 1000385: 11350560,
 1000386: 11350624,
 1000621: 11530740,
 1000622: 11530740,
 1000623: 11530730,
 1000862: 11650600,
 1000246: 11260565,
 1000023: 11110680,
 1000024: 11110680,
 1000146: 11215830,
 1000147: 11215830,
 1000148: 11215830,
 1000149: 11215830,
 1000244: 11260575,
 1000542: 11470640,
 1000802: 11620630,
 1000617: 11530770,
 1000618: 11530740,
 1000725: 11560630,
 1000726: 11560550,
 1000727: 11560550,
 1000728: 11560535,
 1000019: 11110710,
 1000020: 11110700,
 1000021: 11110650,
 1000414: 11380580,
 1000415: 11380625,
 1000033: 11140615,
 1000561: 11500611,
 1000562: 11500611,
 1000837: 11620575,
 1000838: 11620735,
 1000839: 11620735,
 1000731: 11560630,
 1000822: 11620685,
 1000823: 11620655,
 1000824: 11620615,
 1000825: 11620565,
 1000826: 11620625,
 1000827: 11620595,
 1000828: 11620595,
 1000947: 11710600,
 1000948: 11710600,
 1000582: 11500590,
 1000583: 11500620,
 1000683: 11560650,
 1000684: 11560605,
 1000685: 11560605,
 1000686: 11560605,
 1000399: 11380560,
 1000400: 11380560,
 1000401: 11380625,
 1000619: 11530740,
 1000620: 11530720,
 1000283: 11290640,
 1000284: 11290575,
 1000030: 11140615,
 1000031: 11140665,
 1000032: 11140665,
 1000080: 11170625,
 1000081: 11170625,
 1000082: 11170625,
 1000083: 11170530,
 1000084: 11170685,
 1000478: 11440730,
 1000479: 11440700,
 1000480: 11440600,
 1000481: 11440720,
 1000482: 11440720,
 1000911: 11680565,
 1000584: 11500570,
 1000687: 11560535,
 1000746: 11590510,
 1001000: 11740685,
 1001001: 11740600,
 1001002: 11740530,
 1001003: 11740650,
 1000690: 11560560,
 1000285: 11290600,
 1000286: 11290715,
 1000559: 11500560,
 1000560: 11500560,
 1000416: 11380580,
 1000417: 11380600,
 1000418: 11380600,
 1000090: 11200615,
 1000091: 11200650,
 1000092: 11200670,
 1000093: 11200540,
 1000225: 11260620,
 1000160: 11215850,
 1000161: 11215770,
 1000863: 11650590,
 1000705: 11560630,
 1000706: 11560630,
 1000707: 11560710,
 1000708: 11560710,
 1000709: 11560700,
 1000801: 11620630,
 1000448: 11410720,
 1000691: 11560560,
 1000803: 11620630,
 1000804: 11620525,
 1000805: 11620735,
 1000806: 11620735,
 1000807: 11620765,
 1000940: 11710550,
 1000419: 11380600,
 1000420: 11380600,
 1000397: 11380650,
 1000079: 11170625,
 1000025: 11110580,
 1000864: 11650590,
 1000865: 11650510,
 1000866: 11650581,
 1000433: 11380551,
 1000434: 11380530,
 1000408: 11380530,
 1000840: 11620745,
 1000640: 11530540,
 1000604: 11500540,
 1000605: 11500615,
 1000606: 11500591,
 1000607: 11500591,
 1000608: 11500520,
 1000710: 11560620,
 1000711: 11560610,
 1000949: 11710600,
 1000950: 11710580,
 1000951: 11710580,
 1000952: 11710580,
 1000953: 11710562,
 1000954: 11710650,
 1000912: 11680580,
 1000026: 11110560,
 1000027: 11110530,
 1000458: 11440630,
 1000459: 11440600,
 1000087: 11170510,
 1000111: 11200720,
 1000112: 11200720,
 1000113: 11200690,
 1000114: 11200690,
 1000115: 11200690,
 1000116: 11200660,
 1000117: 11200560,
 1000775: 11590540,
 1000642: 11530595,
 1000643: 11530540,
 1000644: 11530540,
 1000645: 11530790,
 1000646: 11530790,
 1000745: 11590510,
 1000713: 11560610,
 1000776: 11590520,
 1000777: 11590520,
 1000778: 11590605,
 1000779: 11590605,
 1000886: 11680521,
 1000887: 11680521,
 1000888: 11680521,
 1000811: 11620525,
 1000004: 11110650,
 1000005: 11110550,
 1000287: 11290715,
 1000432: 11380530,
 1000195: 11230650,
 1000085: 11170660,
 1000086: 11170590,
 1000196: 11230650,
 1000134: 11215740,
 1000135: 11215740,
 1000136: 11215760,
 1000585: 11500530,
 1000586: 11500530,
 1000587: 11500530,
 1000588: 11500570,
 1000589: 11500620,
 1000590: 11500620,
 1000574: 11500615,
 1000575: 11500615,
 1000692: 11560700,
 1000693: 11560720,
 1000694: 11560720,
 1000695: 11560720,
 1000696: 11560720,
 1000550: 11470600,
 1000551: 11470600,
 1000321: 11305545,
 1000322: 11305535,
 1000323: 11305535,
 1000324: 11305535,
 1000325: 11305545,
 1000421: 11380580,
 1000461: 11440585,
 1000162: 11215860,
 1000163: 11215770,
 1000164: 11215840,
 1000165: 11215750,
 1000166: 11215750,
 1000132: 11215870,
 1000301: 11290705,
 1000854: 11650590,
 1000449: 11410720,
 1000450: 11410685,
 1000451: 11410565,
 1000452: 11410565,
 1000453: 11410520,
 1000454: 11410620,
 1000455: 11410620,
 1000456: 11410615,
 1000457: 11410620,
 1000485: 11440680,
 1000486: 11440610,
 1000487: 11440610,
 1000462: 11440585,
 1000463: 11440655,
 1000464: 11440630,
 1000465: 11440680,
 1000466: 11440660,
 1000001: 11110600,
 1000002: 11110710,
 1000003: 11110615,
 1000409: 11380625,
 1000410: 11380530,
 1000393: 11380625,
 1000394: 11380600,
 1000395: 11380560,
 1000396: 11380570,
 1000985: 11740570,
 1000788: 11620625,
 1000789: 11620775,
 1000790: 11620775,
 1000791: 11620775,
 1000792: 11620685,
 1000913: 11680531,
 1000914: 11680531,
 1000915: 11680590,
 1000916: 11680590,
 1000917: 11680590,
 1000918: 11680565,
 1000919: 11680600,
 1000652: 11530730,
 1001034: 11650600,
 1001035: 11680656,
 1001036: 11710641,
 1001037: 11680655,
 1001072: 11590550,
 1001063: 11650531,
 1001064: 11530550,
 1001065: 11680600,
 1001124: 11560535,
 1001125: 11680565,
 1001126: 11470650,
 1001127: 11560540,
 1001128: 11680565,
 1001129: 11680565,
 1001130: 11680565,
 1001131: 11680565,
 1001132: 11560550,
 1001133: 11680565,
 1001134: 11560540,
 1001378: 11410555,
 1001430: 11560535,
 1001431: 11560550,
 1001432: 11560585,
 1001433: 11560605,
 1001434: 11560610,
 1001435: 11560630,
 1001436: 11560650,
 1001455: 11620605,
 1001456: 11620605,
 1001457: 11620615,
 1001458: 11620625,
 1000302: 11290705,
 1000259: 11260575,
 1000260: 11260520,
 1000261: 11290660,
 1000262: 11290810,
 1000263: 11290810,
 1000402: 11380552,
 1001135: 11680510,
 1001136: 11470510,
 1001137: 11740660,
 1001138: 11680565,
 1001139: 11560550,
 1001140: 11680545,
 1001233: 11110615,
 1001234: 11110530,
 1001235: 11110600,
 1001236: 11110540,
 1001237: 11110530,
 1001238: 11230560,
 1001239: 11440740,
 1001240: 11110640,
 1001459: 11620655,
 1001392: 11440710,
 1001393: 11440730,
 1001379: 11410640,
 1001380: 11410660,
 1001381: 11410690,
 1001382: 11410700,
 1001383: 11440555,
 1001384: 11440555,
 1001385: 11440555,
 1001386: 11440630,

## 4. market_gr에 행정동_코드 열 추가

In [21]:
market_gr.head()

     상권_코드  기준_년_코드  기준_분기_코드  점포_수  유사_업종_점포_수
0  1000001     2020         4   201         212
1  1000002     2020         4   115         122
2  1000003     2020         4   284         299
3  1000004     2020         4    73          84
4  1000005     2020         4    76          80

In [22]:
for i in range(1496):
    market_gr.loc[i,'행정동_코드']=Dic[market_gr.loc[i,'상권_코드']]

In [23]:
market_gr.head()

     상권_코드  기준_년_코드  기준_분기_코드  점포_수  유사_업종_점포_수      행정동_코드
0  1000001     2020         4   201         212  11110600.0
1  1000002     2020         4   115         122  11110710.0
2  1000003     2020         4   284         299  11110615.0
3  1000004     2020         4    73          84  11110650.0
4  1000005     2020         4    76          80  11110550.0

In [24]:
market_gr['행정동_코드'] = market_gr['행정동_코드']*100
market_gr['행정동_코드'] = market_gr['행정동_코드'].astype(int)
market_gr.head()

     상권_코드  기준_년_코드  기준_분기_코드  점포_수  유사_업종_점포_수      행정동_코드
0  1000001     2020         4   201         212  1111060000
1  1000002     2020         4   115         122  1111071000
2  1000003     2020         4   284         299  1111061500
3  1000004     2020         4    73          84  1111065000
4  1000005     2020         4    76          80  1111055000

## 5. '행정동_코드'를 '행정동명' 으로 변경

### 행정_법정_매칭_new.txt 데이터 불러오기

In [25]:
name=pd.read_table('행정_법정_매칭_new.txt',sep=',')
name.head()

     행정동  법정동       행정동코드       법정동코드
0  청운효자동  청운동  1111051500  1111010100
1  청운효자동  신교동  1111051500  1111010200
2  청운효자동  궁정동  1111051500  1111010300
3  청운효자동  효자동  1111051500  1111010400
4  청운효자동  창성동  1111051500  1111010500

In [26]:
name=name.drop(['법정동','법정동코드'], axis=1)
name.drop_duplicates(subset=None, keep='first', inplace=True)
name.head()

      행정동       행정동코드
0   청운효자동  1111051500
10    사직동  1111053000
22    삼청동  1111054000
29    부암동  1111055000
32    평창동  1111056000

In [27]:
name.reset_index(drop=True, inplace=True)
name.head()

     행정동       행정동코드
0  청운효자동  1111051500
1    사직동  1111053000
2    삼청동  1111054000
3    부암동  1111055000
4    평창동  1111056000

### 행정동코드를 행정동명으로 바꾸는 dictionary 생성

In [28]:
Dic2=dict(zip(name['행정동코드'], name['행정동']))

In [29]:
Dic2

{1111051500: '청운효자동',
 1111053000: '사직동',
 1111054000: '삼청동',
 1111055000: '부암동',
 1111056000: '평창동',
 1111057000: '무악동',
 1111058000: '교남동',
 1111060000: '가회동',
 1111061500: '종로1.2.3.4가동',
 1111063000: '종로5.6가동',
 1111064000: '이화동',
 1111065000: '혜화동',
 1111067000: '창신제1동',
 1111068000: '창신제2동',
 1111069000: '창신제3동',
 1111070000: '숭인제1동',
 1111071000: '숭인제2동',
 1114052000: '소공동',
 1114054000: '회현동',
 1114055000: '명동',
 1114057000: '필동',
 1114058000: '장충동',
 1114059000: '광희동',
 1114060500: '을지로동',
 1114061500: '신당동',
 1114062500: '다산동',
 1114063500: '약수동',
 1114064500: '청구동',
 1114065000: '신당제5동',
 1114066500: '동화동',
 1114067000: '황학동',
 1114068000: '중림동',
 1117051000: '후암동',
 1117052000: '용산2가동',
 1117053000: '남영동',
 1117055500: '청파동',
 1117056000: '원효로제1동',
 1117057000: '원효로제2동',
 1117058000: '효창동',
 1117059000: '용문동',
 1117062500: '한강로동',
 1117063000: '이촌제1동',
 1117064000: '이촌제2동',
 1117065000: '이태원제1동',
 1117066000: '이태원제2동',
 1117068500: '한남동',
 1117069000: '서빙고동',
 1117070000: '보광동',
 1120052000: '왕십리제2동',
 1120053500: '왕십리도선동',
 1120054000: '마장동',
 1120055000: '사근동',
 1120056000: '행당제1동',
 1120057000: '행당제2동',
 1120058000: '응봉동',
 1120059000: '금호1가동',
 1120061500: '금호2.3가동',
 1120062000: '금호4가동',
 1120064500: '옥수동',
 1120065000: '성수1가제1동',
 1120066000: '성수1가제2동',
 1120067000: '성수2가제1동',
 1120069000: '성수2가제3동',
 1120072000: '송정동',
 1120079000: '용답동',
 1121571000: '화양동',
 1121573000: '군자동',
 1121574000: '중곡제1동',
 1121575000: '중곡제2동',
 1121576000: '중곡제3동',
 1121577000: '중곡제4동',
 1121578000: '능동',
 1121581000: '광장동',
 1121582000: '자양제1동',
 1121583000: '자양제2동',
 1121584000: '자양제3동',
 1121584700: '자양제4동',
 1121585000: '구의제1동',
 1121586000: '구의제2동',
 1121587000: '구의제3동',
 1123053600: '용신동',
 1123054500: '제기동',
 1123056000: '전농제1동',
 1123057000: '전농제2동',
 1123060000: '답십리제1동',
 1123061000: '답십리제2동',
 1123065000: '장안제1동',
 1123066000: '장안제2동',
 1123070500: '청량리동',
 1123071000: '회기동',
 1123072000: '휘경제1동',
 1123073000: '휘경제2동',
 1123074000: '이문제1동',
 1123075000: '이문제2동',
 1126052000: '면목제2동',
 1126054000: '면목제4동',
 1126055000: '면목제5동',
 1126056500: '면목본동',
 1126057000: '면목제7동',
 1126057500: '면목제3.8동',
 1126058000: '상봉제1동',
 1126059000: '상봉제2동',
 1126060000: '중화제1동',
 1126061000: '중화제2동',
 1126062000: '묵제1동',
 1126063000: '묵제2동',
 1126065500: '망우본동',
 1126066000: '망우제3동',
 1126068000: '신내1동',
 1126069000: '신내2동',
 1129052500: '성북동',
 1129055500: '삼선동',
 1129057500: '동선동',
 1129058000: '돈암제1동',
 1129059000: '돈암제2동',
 1129060000: '안암동',
 1129061000: '보문동',
 1129062000: '정릉제1동',
 1129063000: '정릉제2동',
 1129064000: '정릉제3동',
 1129065000: '정릉제4동',
 1129066000: '길음제1동',
 1129068500: '길음제2동',
 1129070500: '종암동',
 1129071500: '월곡제1동',
 1129072500: '월곡제2동',
 1129076000: '장위제1동',
 1129077000: '장위제2동',
 1129078000: '장위제3동',
 1129081000: '석관동',
 1130553400: '삼양동',
 1130553500: '미아동',
 1130554500: '송중동',
 1130555500: '송천동',
 1130557500: '삼각산동',
 1130559500: '번1동',
 1130560300: '번2동',
 1130560800: '번3동',
 1130561500: '수유1동',
 1130562500: '수유2동',
 1130563500: '수유3동',
 1130564500: '우이동',
 1130566000: '인수동',
 1132051100: '창제1동',
 1132051200: '창제2동',
 1132051300: '창제3동',
 1132051400: '창제4동',
 1132051500: '창제5동',
 1132052100: '도봉제1동',
 1132052200: '도봉제2동',
 1132066000: '쌍문제1동',
 1132067000: '쌍문제2동',
 1132068000: '쌍문제3동',
 1132068100: '쌍문제4동',
 1132069000: '방학제1동',
 1132070000: '방학제2동',
 1132071000: '방학제3동',
 1135056000: '월계1동',
 1135057000: '월계2동',
 1135058000: '월계3동',
 1135059500: '공릉1동',
 1135060000: '공릉2동',
 1135061100: '하계1동',
 1135061200: '하계2동',
 1135061900: '중계본동',
 1135062100: '중계1동',
 1135062400: '중계4동',
 1135062500: '중계2.3동',
 1135063000: '상계1동',
 1135064000: '상계2동',
 1135066500: '상계3.4동',
 1135067000: '상계5동',
 1135069500: '상계6.7동',
 1135070000: '상계8동',
 1135071000: '상계9동',
 1135072000: '상계10동',
 1138051000: '녹번동',
 1138052000: '불광제1동',
 1138053000: '불광제2동',
 1138055100: '갈현제1동',
 1138055200: '갈현제2동',
 1138056000: '구산동',
 1138057000: '대조동',
 1138058000: '응암제1동',
 1138059000: '응암제2동',
 1138060000: '응암제3동',
 1138062500: '역촌동',
 1138063100: '신사제1동',
 1138063200: '신사제2동',
 1138064000: '증산동',
 1138065000: '수색동',
 1138069000: '진관동',
 1141052000: '천연동',
 1141055500: '북아현동',
 1141056500: '충현동',
 1141058500: '신촌동',
 1141061500: '연희동',
 1141062000: '홍제제1동',
 1141064000: '홍제제3동',
 1141065500: '홍제제2동',
 1141066000: '홍은제1동',
 1141068500: '홍은제2동',
 1141069000: '남가좌제1동',
 1141070000: '남가좌제2동',
 1141071000: '북가좌제1동',
 1141072000: '북가좌제2동',
 1144055500: '아현동',
 1144056500: '공덕동',
 1144058500: '도화동',
 1144059000: '용강동',
 1144060000: '대흥동',
 1144061000: '염리동',
 1144063000: '신수동',
 1144065500: '서강동',
 1144066000: '서교동',
 1144068000: '합정동',
 1144069000: '망원제1동',
 1144070000: '망원제2동',
 1144071000: '연남동',
 1144072000: '성산제1동',
 1144073000: '성산제2동',
 1144074000: '상암동',
 1147051000: '목1동',
 1147052000: '목2동',
 1147053000: '목3동',
 1147054000: '목4동',
 1147055000: '목5동',
 1147056000: '신월1동',
 1147057000: '신월2동',
 1147058000: '신월3동',
 1147059000: '신월4동',
 1147060000: '신월5동',
 1147061000: '신월6동',
 1147061100: '신월7동',
 1147062000: '신정1동',
 1147063000: '신정2동',
 1147064000: '신정3동',
 1147065000: '신정4동',
 1147067000: '신정6동',
 1147068000: '신정7동',
 1150051000: '염창동',
 1150052000: '등촌제1동',
 1150053000: '등촌제2동',
 1150053500: '등촌제3동',
 1150054000: '화곡제1동',
 1150055000: '화곡제2동',
 1150056000: '화곡제3동',
 1150057000: '화곡제4동',
 1150059000: '화곡본동',
 1150059100: '화곡제6동',
 1150059300: '화곡제8동',
 1150060300: '가양제1동',
 1150060400: '가양제2동',
 1150060500: '가양제3동',
 1150061100: '발산제1동',
 1150061500: '우장산동',
 1150062000: '공항동',
 1150063000: '방화제1동',
 1150064000: '방화제2동',
 1150064100: '방화제3동',
 1153051000: '신도림동',
 1153052000: '구로제1동',
 1153053000: '구로제2동',
 1153054000: '구로제3동',
 1153055000: '구로제4동',
 1153056000: '구로제5동',
 1153059500: '가리봉동',
 1153072000: '고척제1동',
 1153073000: '고척제2동',
 1153074000: '개봉제1동',
 1153075000: '개봉제2동',
 1153076000: '개봉제3동',
 1153077000: '오류제1동',
 1153078000: '오류제2동',
 1153079000: '수궁동',
 1153080000: '항동',
 1154551000: '가산동',
 1154561000: '독산제1동',
 1154562000: '독산제2동',
 1154563000: '독산제3동',
 1154564000: '독산제4동',
 1154567000: '시흥제1동',
 1154568000: '시흥제2동',
 1154569000: '시흥제3동',
 1154570000: '시흥제4동',
 1154571000: '시흥제5동',
 1156051500: '영등포본동',
 1156053500: '영등포동',
 1156054000: '여의동',
 1156055000: '당산제1동',
 1156056000: '당산제2동',
 1156058500: '도림동',
 1156060500: '문래동',
 1156061000: '양평제1동',
 1156062000: '양평제2동',
 1156063000: '신길제1동',
 1156065000: '신길제3동',
 1156066000: '신길제4동',
 1156067000: '신길제5동',
 1156068000: '신길제6동',
 1156069000: '신길제7동',
 1156070000: '대림제1동',
 1156071000: '대림제2동',
 1156072000: '대림제3동',
 1159051000: '노량진제1동',
 1159052000: '노량진제2동',
 1159053000: '상도제1동',
 1159054000: '상도제2동',
 1159055000: '상도제3동',
 1159056000: '상도제4동',
 1159060500: '흑석동',
 1159062000: '사당제1동',
 1159063000: '사당제2동',
 1159064000: '사당제3동',
 1159065000: '사당제4동',
 1159065100: '사당제5동',
 1159066000: '대방동',
 1159067000: '신대방제1동',
 1159068000: '신대방제2동',
 1162052500: '보라매동',
 1162054500: '청림동',
 1162056500: '성현동',
 1162057500: '행운동',
 1162058500: '낙성대동',
 1162059500: '청룡동',
 1162060500: '은천동',
 1162061500: '중앙동',
 1162062500: '인헌동',
 1162063000: '남현동',
 1162064500: '서원동',
 1162065500: '신원동',
 1162066500: '서림동',
 1162068500: '신사동',
 1162069500: '신림동',
 1162071500: '난향동',
 1162072500: '조원동',
 1162073500: '대학동',
 1162074500: '삼성동',
 1162076500: '미성동',
 1162077500: '난곡동',
 1165051000: '서초1동',
 1165052000: '서초2동',
 1165053000: '서초3동',
 1165053100: '서초4동',
 1165054000: '잠원동',
 1165055000: '반포본동',
 1165056000: '반포1동',
 1165057000: '반포2동',
 1165058000: '반포3동',
 1165058100: '반포4동',
 1165059000: '방배본동',
 1165060000: '방배1동',
 1165061000: '방배2동',
 1165062000: '방배3동',
 1165062100: '방배4동',
 1165065100: '양재1동',
 1165065200: '양재2동',
 1165066000: '내곡동',
 1168051000: '신사동',
 1168052100: '논현1동',
 1168053100: '논현2동',
 1168054500: '압구정동',
 1168056500: '청담동',
 1168058000: '삼성1동',
 1168059000: '삼성2동',
 1168060000: '대치1동',
 1168061000: '대치2동',
 1168063000: '대치4동',
 1168064000: '역삼1동',
 1168065000: '역삼2동',
 1168065500: '도곡1동',
 1168065600: '도곡2동',
 1168066000: '개포1동',
 1168067000: '개포2동',
 1168069000: '개포4동',
 1168070000: '세곡동',
 1168072000: '일원본동',
 1168073000: '일원1동',
 1168074000: '일원2동',
 1168075000: '수서동',
 1171051000: '풍납1동',
 1171052000: '풍납2동',
 1171053100: '거여1동',
 1171053200: '거여2동',
 1171054000: '마천1동',
 1171055000: '마천2동',
 1171056100: '방이1동',
 1171056200: '방이2동',
 1171056600: '오륜동',
 1171057000: '오금동',
 1171058000: '송파1동',
 1171059000: '송파2동',
 1171060000: '석촌동',
 1171061000: '삼전동',
 1171062000: '가락본동',
 1171063100: '가락1동',
 1171063200: '가락2동',
 1171064100: '문정1동',
 1171064200: '문정2동',
 1171064600: '장지동',
 1171064700: '위례동',
 1171065000: '잠실본동',
 1171067000: '잠실2동',
 1171068000: '잠실3동',
 1171069000: '잠실4동',
 1171071000: '잠실6동',
 1171072000: '잠실7동',
 1174051500: '강일동',
 1174052500: '상일제1동',
 1174052600: '상일제2동',
 1174053000: '명일제1동',
 1174054000: '명일제2동',
 1174055000: '고덕제1동',
 1174056000: '고덕제2동',
 1174057000: '암사제1동',
 1174058000: '암사제2동',
 1174059000: '암사제3동',
 1174060000: '천호제1동',
 1174061000: '천호제2동',
 1174062000: '천호제3동',
 1174064000: '성내제1동',
 1174065000: '성내제2동',
 1174066000: '성내제3동',
 1174068500: '길동',
 1174069000: '둔촌제1동',
 1174070000: '둔촌제2동'}

### market_gr에 행정동명 추가

In [30]:
market_gr.head()

     상권_코드  기준_년_코드  기준_분기_코드  점포_수  유사_업종_점포_수      행정동_코드
0  1000001     2020         4   201         212  1111060000
1  1000002     2020         4   115         122  1111071000
2  1000003     2020         4   284         299  1111061500
3  1000004     2020         4    73          84  1111065000
4  1000005     2020         4    76          80  1111055000

In [31]:
for i in range(1496):
    market_gr.loc[i,'행정동']=Dic2.get(market_gr.loc[i,'행정동_코드'])

In [32]:
market_gr.head()

     상권_코드  기준_년_코드  기준_분기_코드  점포_수  유사_업종_점포_수      행정동_코드          행정동
0  1000001     2020         4   201         212  1111060000          가회동
1  1000002     2020         4   115         122  1111071000        숭인제2동
2  1000003     2020         4   284         299  1111061500  종로1.2.3.4가동
3  1000004     2020         4    73          84  1111065000          혜화동
4  1000005     2020         4    76          80  1111055000          부암동